### ISSUE TITLE
ACNA-271 - aio config and aio config:get without key should return valid JSON

### ISSUE THREAD

**Issue by fmeschbe** [adobe/aio-cli-plugin-config#36]
### Expected Behaviour

Getting the complete configuration with `aio config` or `aio config:get` (no key) should return just a JSON document of the current configuration which would also be suitable for input to, say, `jq`.

Example empty configuration:

```sh
$ aio config:get
{}
```

Example configuration with one property piping out to `jq`:

```sh
$ aio config:set test 5
$ aio config | jq .
{
  "test": "5"
}
```

### Actual Behaviour

The actual output prints a _null_ prototype and then the object in plain JavaScript but non-JSON compliant way:

Example empty configuration:

```sh
$ aio config:get
[Object: null prototype] {}
```

Example configuration with one property:

```sh
$ aio config:set test 5
$ aio config
[Object: null prototype] { test: '5' }
```

### Reproduce Scenario (including but not limited to)

See examples above

#### Steps to Reproduce

See examples above

#### Logs taken while reproducing problem

**Comment by fmeschbe** [comment]
Alternatively to PR #37, we could also introduce a new flag parameter `-j`/`--json` to ask the result to be formatted as valid JSON.

So the second example would be

```sh
$ aio config
{ test: "5" }
```
or as JSON

```sh
$ aio config -j
{ "test": "5" }
```

Patch would be:

```patch
diff --git a/src/commands/config/get.js b/src/commands/config/get.js
index d4fcd96..64d2b9d 100755
--- a/src/commands/config/get.js
+++ b/src/commands/config/get.js
@@ -10,23 +10,24 @@ OF ANY KIND, either express or implied. See the License for the specific languag
 governing permissions and limitations under the License.
 */
 
-const { Command } = require('@oclif/command')
+const { Command, flags } = require('@oclif/command')
 const Conf = require('conf')
 
 class GetCommand extends Command {
   async run () {
-    const { args } = this.parse(GetCommand)
+    const { args, flags } = this.parse(GetCommand)
 
-    let retVal = await this.get(args.key)
+    let retVal = await this.get(args.key, flags.json)
     if (retVal) {
       this.log(retVal)
     }
     return retVal
   }
 
-  async get (key) {
+  async get (key, json) {
     const conf = new Conf()
-    return (key) ? conf.get(key) : JSON.stringify(Object.assign({}, conf.store))
+    const result = (key) ? conf.get(key) : Object.assign({}, conf.store)
+    return (json) ? JSON.stringify(result) : result
   }
 }
 
@@ -36,4 +37,8 @@ GetCommand.args = [
   { name: 'key' }
 ]
 
+GetCommand.flags = {
+  json: flags.boolean({ char: 'j', description: 'format as JSON' })
+}
+
 module.exports = GetCommand
```

Maybe also to issues/PR: One to fix the outcome of `aio config` and one for the `-j`/`--json` parameter.

Please advise !

**Comment by goya** [comment]
i am working on a pull request with is as well as some other stuff. it's on my fork goya/aio-cli-plugin-config

**Comment by shazron** [comment]
Felix, I'm trying to repro:
```
$ aio config:set test 5
$ aio config
[Object: null prototype] { test: '5' }
```

But I get:
```
$ aio config:set test 5
$ aio config
{ test: '5' }
```

My version is:
```
$ aio --version
@adobe/aio-cli/1.5.0 darwin-x64 node-v8.11.4
```

**Comment by goya** [comment]
got a pr for this. that isn’t valid json.

i mean a pr eventually.

-brett
adobe.com

________________________________

**Comment by shazron** [comment]
ah yes, I missed that part of "test" wasn't in double quotes, nor the "5".

**Comment by shazron** [comment]
@goya seems there is a PR already at #37? Confused

**Comment by goya** [comment]
“pr eventually” :)

-brett
adobe.com

________________________________

**Comment by goya** [comment]
also json stringify in the or doesn’t nest well.

**Comment by fmeschbe** [comment]
> My version is:
> ```sh
> $ aio --version
> @adobe/aio-cli/1.5.0 darwin-x64 node-v8.11.4
> ```

Mine -- note NodeJS 10:

```sh
$ aio --version
@adobe/aio-cli/1.5.0 darwin-x64 node-v10.15.3
```

> @goya seems there is a PR already at #37? Confused

Yes, @shazron PR #37 attacks the problem in two ways: (1) generating proper JSON result (instead of JavaScript serialisation) and (2) Removing spurious prototype printing.

The problem with PR #37 is that when `new GetCommand().get()` is called, the JSON serialisation is returned instead of the plain object. I think that is probably bad. So my comment splits this into (a) making sure, there is no `null` prototype on the object returned and (b) a new command line flag is added to explicitly ask for JSON.

I think, I am going to update PR #37 to only do the prototype thing and create a new issue for just asking for JSON.

**Comment by fmeschbe** [comment]
I have updated the patch to revert the changes to the `get()` function but instead implement the `-j`/`--json` flag in the `run()` method as this is really about the command line not about the inner function of getting configuration.

**Comment by fmeschbe** [comment]
@goya I see your PR #38. Does that fully cover this issue ? If so, please feel free to just close this issue. I already closed off my PR #37.

**Comment by purplecabbage** [comment]
@goya pr does cover this, as well as allowing for -y / --yaml output
Default output is hjson for readability

**Comment by goya** [comment]
yeah forgot to add the issue to a commit, had the change before this issue was opened.
